basePath: /
definitions:
  board.BoardMsg:
    properties:
      boardId:
        type: integer
      content:
        type: string
      createdAt:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      userEmail:
        type: string
    type: object
  board.BoardsMsg:
    properties:
      boards:
        items:
          $ref: '#/definitions/board.BoardMsg'
        type: array
    type: object
  board.CreateBoardRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  server.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  user.JoinRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  user.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.UserMsg:
    properties:
      email:
        type: string
      name:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: { }
  title: MicroApp documentation
  version: 1.0.0
paths:
  /v1/board:
    get:
      consumes:
        - application/json
      parameters:
        - in: query
          name: title
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/board.BoardsMsg'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/server.Error'
      summary: 게시판 목록 조회 API
    post:
      consumes:
        - application/json
      parameters:
        - description: CreateBoardRequest
          in: body
          name: board.CreateBoardRequest
          required: true
          schema:
            $ref: '#/definitions/board.CreateBoardRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/board.BoardMsg'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/server.Error'
      summary: 게시판 등록 API
  /v1/board/{id}:
    get:
      consumes:
        - application/json
      parameters:
        - description: Board ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/board.BoardMsg'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/server.Error'
      summary: 게시판 조회 API
  /v1/join:
    post:
      consumes:
        - application/json
      parameters:
        - description: JoinRequest
          in: body
          name: JoinRequest
          required: true
          schema:
            $ref: '#/definitions/user.JoinRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserMsg'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/server.Error'
      summary: 회원가입 API
  /v1/login:
    post:
      consumes:
        - application/json
      parameters:
        - description: LoginRequest
          in: body
          name: LoginRequest
          required: true
          schema:
            $ref: '#/definitions/user.LoginRequest'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserMsg'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/server.Error'
      summary: 로그인 API
swagger: "2.0"
